Disable phpVersion in phpstan config due to enum case bug in 2.1.44
Setting phpVersion to 80500 (or 80400) triggers an internal phpstan
error: "This enum case does not have a value" in the PHP 8 signature
map provider. Commenting out until fixed upstream.